name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: print docker password
      run: echo "${{ secrets.DOCKER_PASSWORD }}"
    - name: print docker user
      run: echo "${{ secrets.DOCKER_USER }}"
    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yangbobo046/fastchat:latest
